### ISSUE TITLE
Please consider renaming to gatekeep

### ISSUE THREAD

**Issue by Geometer1729** [nodusclient/guardian#2]

**Comment by JohnShiozo** [comment]
Yes

**Comment by R2D2VaderBeef** [comment]
I genuinely had the same thought right now. Please do! It would be amazing.

**Comment by hjk321** [comment]
What would that do, except create even more confusion?

**Comment by R2D2VaderBeef** [comment]
Then, the three tools made by Nodus would be called gaslight, gatekeep, and girlboss. For people wondering what we're talking about, it's a meme which is explained [here](https://knowyourmeme.com/memes/gaslight-gatekeep-girlboss). 

As a name, it would technically work as well as "guardian", because like being a guardian of the message contexts, it's 'gatekeeping' them from Mojang.

**Comment by ebay-kid** [comment]
They've already planned another one called Gatekeep, but I'm not sure of the release date (and nobody knows what it does).

**Comment by R3Ked** [comment]
make gatekeep report every message sent in a server, this will overflow the report system with garbage reports and nobody at mojang would be able to get any work done
maybe spoof which account sent the report too idk
